### ISSUE TITLE
New sources files

### ISSUE THREAD

**Issue by emmamarichal** [etunni/suranna#1]
Hi @etunni,

I noticed that this version on the repo has a better language support than the one on the API.
Do you have, by any chance, a .glyphs file in order to update the font?

Thanks!
Emma

**Comment by etunni** [comment]
HI @emmamarichal ,
This work isn't my, I remember that I collaborated as external assistent in various typographic projects with more than one designer long time ago  —10 years— , but don't have the final sources.

Cheers,
Edu

**Comment by emmamarichal** [comment]
No problem, I can try to update the font from what I have in the repo. Thanks!
